spring:
  datasource:
    url: jdbc:h2:mem:spms_library;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    generate-ddl: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /console

  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog-master-h2.xml'
