server:
  port: 8050

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'

      routes:
      - id: buyer-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/buyers/**

      - id: season-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/seasons/**

      - id: garment-type-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/garmentTypes/**

      - id: line-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/lines/**

      - id: section-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/sections/**

      - id: department-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/departments/**

      - id: machine-type-resource
        uri: lb://proman-service
        predicates:
        - Path=/v1/api/machineTypes/**

      - id: machine-resource
        uri: lb://proman-service
        predicates:
        - Path=/v1/api/machines/**

      - id: operation-resource
        uri: lb://proman-service
        predicates:
        - Path=/v1/api/operations/**

      - id: operation-bulletin-template-resource
        uri: lb://proman-service
        predicates:
        - Path=/v1/api/tOperationBulletins/**

      - id: operation-bulletin-resource
        uri: lb://proman-service
        predicates:
        - Path=/v1/api/operationBulletins/**

      - id: order-resource
        uri: lb://proman-service
        predicates:
        - Path=/v1/api/orders/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
