server:
  port: 8050

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: buyer-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/buyers/**

      - id: season-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/seasons/**

      - id: garment-type-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/garmentTypes/**

      - id: line-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/lines/**

      - id: section-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/sections/**

      - id: department-resource
        uri: lb://library-service
        predicates:
        - Path=/v1/api/departments/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
