server:
  port: 8050

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: library-service
        uri: lb://library-service
        predicates:
        - Path=/v1/api/buyers/**
        # - Path=/v1/api/seasons/**
        # - Path=/v1/api/garmentTypes/**
        # - Path=/v1/api/lines/**
        # - Path=/v1/api/sections/**
        # - Path=/v1/api/departments/**
        filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@userKeyResolver}'
#            redis-rate-limiter.replenishRate: 2
#            redis-rate-limiter.burstCapacity: 2
#        - RewritePath=/api/(?<books>.*), /$\{books}
        - name: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward:/v1/api/fallback

management:
  endpoints:
    web:
      exposure:
        include: '*'
