app:
  home: SPMS_HOME

server:
  port: 8052
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
#  connection-timeout: -1
#  tomcat:
#    max-http-post-size: 1048576

spring:
  datasource:
    ###### PostgreSQL Configuration #######
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spms_proman
    # username: mdzahidraza
    # password: zahid

  jpa:
    generate-ddl: true
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog-master.xml'
    
#  mail:
#    protocol: smtp
#    test-connection: false
#    host: smtp.gmail.com
#    port: 587
#    from: noreply@jaza-soft.com
#    username: admin@jaza-soft.com
#    password: tuksysvicjegaufu
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true


#security:
#  filter-order: 0
#  oauth2:
#    resource:
#      id: SPMS_RESOURCE
#      filter-order: 3

#liquibase:
#  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


